version: "3.8"

services:
  mongodb:
    container_name: mongodb-database
    image: mongo:4.4
    volumes:
      - ./data:/data/db
    ports:
      - '27017:27017'

  app:
    container_name: nodejs-app
    restart: always
    depends_on: 
      - mongodb
    ports:
    - "8080:8080"
    build: .
    links:
     - mongodb